openapi: '3.0.3'
info:
  title: 'PSBAPP Greens API'
  version: '2021-05-27'

paths:
  /p/{placeId}:
    parameters:
      - in: path
        schema:
          type: string
        name: placeId
        required: true
    get:
      tags: [End User]
      description: Ottieni informazioni su un luogo
      responses:
        200:
          description: Informazioni sul luogo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceInfo'
        444:
          description: Luogo non esistente
  /categories:
    get:
      tags: [End User]
      description: Ottieni la lista di categorie
      responses:
        200:
          description: Lista di categorie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriesList'
  ##### SEARCH API
  /search/p:
    get:
      tags: [End User, Search]
      parameters:
        - name: q
          in: query
          description: >-
            The text for full text search on all fields
          required: false
          schema:
            type: string
        - name: near
          in: query
          description: >-
            Latitude and longitude for the search
          required: false
          schema:
            type: string
            example: 45.1234,11.3749
            pattern: '\d{1,2}(.\d*)\,\d{1,2}(.\d*)'
        - name: cat
          in: query
          description: >-
            Category filter for the search
          required: false
          schema:
            type: string
      summary: Search places
      description: >-
        At least one of the 'q' or the 'near' parameters is required
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceList'

components:
  schemas:
    CategoriesList:
      type: object
      required:
        - categories
      properties:
        categories:
          type: array
          items:
            type: string
    PlaceList:
      type: object
      properties:
        places:
          type: array
          items:
            $ref: '#/components/schemas/PlaceInfo'
    PlaceInfo:
      type: object
      properties:
        placeId:
          type: string
          example: thn1
        istatCode:
          type: string
          example: '24100'
        name:
          type: string
          example: Parco giochi via Milano
        city:
          type: string
          example: Thiene
        province:
          type: string
          example: VI
        category:
          type: string
          example: Parchi urbani
        area:
          type: string
          example: 1045
        lat:
          type: string
          example: 45.50593824
        lon:
          type: string
          example: 12.293843284
        searchable:
          type: boolean

tags:
  - name: End User
    description: Chiamate utilizzate dall'end user, non sono autenticate.
  - name: Search
    description: Chiamate per cercare i luoghi
